name: Deploy Backend to Azure Container Apps

on:
  push:
    branches:
      - langserve-openai

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Docker image tag to commit SHA
      run: echo "DOCKER_IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: deviesprbot.azurecr.io
        username: ${{ secrets.DEVIES_PR_ACR_USERNAME }}
        password: ${{ secrets.DEVIES_PR_ACR_PASSWORD }}

    - name: Build and Push Docker Images (Compose)
      run: |
        docker-compose -f docker-compose.yaml build
        docker-compose -f docker-compose.yaml push

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-compose-deploy-action@v1
      with:
        compose-file: docker-compose.yaml
        registry-url: deviesprbot.azurecr.io
        registry-username: ${{ secrets.DEVIES_PR_ACR_USERNAME }}
        registry-password: ${{ secrets.DEVIES_PR_ACR_PASSWORD }}
        container-app-env: deviesprbot-env
        resource-group: DeviesBlogGPT



