name: Deploy Backend to Azure VM

on:
  push:
    branches:
      - langserve-openai

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # Add user to docker group and ensure permissions are set
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
          
          # Pull the pgvector image
          docker pull pgvector/pgvector:pg16

          # Clone the repository
          cd ~
          ssh-add -D
          ssh-add ~/.ssh/id_rsa
          rm -rf chat-langchain
          git clone git@github.com:DeviesDevelopment/chat-langchain.git
          cd chat-langchain
          git checkout langserve-openai
          git pull origin langserve-openai

          # Stop and remove the existing container if it exists
          docker stop pgvector-container || true
          docker rm pgvector-container || true
          docker stop deviesprbot-container || true
          docker rm deviesprbot-container || true

          # Build the Docker image
          docker rmi -f deviesprbot || true
          docker build -t deviesprbot .
          
          # Run the pgvector with the network
          docker run -d \
            --name pgvector-container \
            --network langchain-network \
            -p 6024:5432 \
            -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            -e POSTGRES_DB=langchain \
            pgvector/pgvector:pg16
          
          # Run the new container with environment variables and network
          docker run -d \
            --name deviesprbot-container \
            --network langchain-network \
            -p 8080:8080 \
            -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            -e POSTGRES_DB_CONN="${{ secrets.POSTGRES_DB_CONN }}" \
            -e DB_INDEX_NAME="${{ secrets.DB_INDEX_NAME }}" \
            -e USER_AGENT="${{ secrets.USER_AGENT }}" \
            -e AZURE_BLOB_CONN="${{ secrets.AZURE_BLOB_CONN }}" \
            -e AZURE_BLOB_CONTAINER="${{ secrets.AZURE_BLOB_CONTAINER }}" \
            -e MPLCONFIGDIR="${{ secrets.MPLCONFIGDIR }}" \
            -e NLTK_DATA="${{ secrets.NLTK_DATA }}" \
            -e XDG_CACHE_HOME="${{ secrets.XDG_CACHE_HOME }}" \
            deviesprbot
          
          # Remove the git repo
          rm -rf chat-langchain


